
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 09 04:44:33 CST 2020
//----------------------------------------------------

package CUP;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FUNCTION = 19;
  public static final int OP_REL = 29;
  public static final int INCREMENT = 33;
  public static final int CHAR = 38;
  public static final int BETWEEN = 7;
  public static final int MATRIX = 40;
  public static final int CHAR_ELEMENT = 18;
  public static final int ARRAY = 39;
  public static final int FOR = 23;
  public static final int CON_OR = 35;
  public static final int MAIN = 28;
  public static final int IF_SWITCH = 20;
  public static final int ID = 42;
  public static final int BOOLEAN = 37;
  public static final int EOF = 0;
  public static final int RETURN = 25;
  public static final int CLOSE_PARENTESIS = 5;
  public static final int TRUE = 15;
  public static final int error = 1;
  public static final int COMA = 10;
  public static final int OPEN_SQR_BRACKET = 8;
  public static final int NULL = 14;
  public static final int NUMBER = 43;
  public static final int MOD = 32;
  public static final int CIN = 26;
  public static final int OP_MULTI_DIV = 31;
  public static final int ERROR = 2;
  public static final int COLON = 11;
  public static final int ELSE = 24;
  public static final int OP_SUM = 30;
  public static final int OPEN_PARENTESIS = 4;
  public static final int CLOSE_BLOCK = 3;
  public static final int VARIABLE = 41;
  public static final int TO = 27;
  public static final int NEW_LINE = 13;
  public static final int WHILE = 22;
  public static final int INTENGER = 36;
  public static final int CLOSE_SQR_BRACKET = 9;
  public static final int STRING = 17;
  public static final int CON_AND = 34;
  public static final int FALSE = 16;
  public static final int BACK_SLASH = 12;
  public static final int PRINT = 21;
  public static final int PYC = 6;
}

