
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Sep 19 17:44:13 CST 2020
//----------------------------------------------------

package CUP;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ifSwitch = 20;
  public static final int closeSqrBracket = 7;
  public static final int closeParentesis = 4;
  public static final int function = 19;
  public static final int True = 32;
  public static final int plus = 27;
  public static final int mod = 34;
  public static final int apostrophe = 11;
  public static final int array = 17;
  public static final int Default = 35;
  public static final int coma = 8;
  public static final int multiplication = 42;
  public static final int orEqual = 25;
  public static final int equalTo = 23;
  public static final int conAnd = 38;
  public static final int Return = 36;
  public static final int While = 21;
  public static final int To = 30;
  public static final int ID = 28;
  public static final int For = 22;
  public static final int EOF = 0;
  public static final int pyc = 5;
  public static final int error = 1;
  public static final int False = 31;
  public static final int colon = 9;
  public static final int matrix = 18;
  public static final int Char = 16;
  public static final int Print = 43;
  public static final int ERROR = 41;
  public static final int integer = 14;
  public static final int closeBlock = 2;
  public static final int increment = 39;
  public static final int quotMark = 10;
  public static final int openParentesis = 3;
  public static final int variable = 13;
  public static final int conOr = 40;
  public static final int noEqualTo = 24;
  public static final int openSqrBracket = 6;
  public static final int than = 26;
  public static final int backslash = 37;
  public static final int Bool = 15;
  public static final int decrement = 33;
  public static final int Main = 12;
  public static final int number = 29;
}

